/**
 * This file is auto-generated from src/config/**/*.yaml and *.csv
 * Do not edit this file directly.
 */
import { NodeCategory, NodeType, NodeExample } from "@/types";

export const nodeExamples: NodeExample[] = [
  {
    id: "call-method",
    nodeType: "call_method" as NodeType,
    category: "CALL_ACTIVITY" as NodeCategory,
    name: "Method Call",
    nameCn: "方法调用",
    description: "执行系统内部定义的函数方法",
    jsonConfig: "{\n  \"nodeId\": \"1201\",\n  \"nodeType\": \"method\",\n  \"sn\": 1,\n  \"nodeName\": \"调用收货方法\",\n  \"action\": {\n    \"ref\": {\n      \"methodId\": \"F1\",\n      \"methodCode\": \"processReceipt\",\n      \"autowiredName\": \"receiptService\"\n    },\n    \"inputParameters\": [\n      {\n        \"sn\": 1,\n        \"code\": \"snItem\",\n        \"paramType\": \"Object\",\n        \"refType\": \"dto\",\n        \"valType\": \"variable\",\n        \"val\": \"item\"\n      }\n    ],\n    \"outputParameter\": {\n      \"receiveVariable\": \"receiptId\"\n    }\n  }\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: method"
  },
  {
    field: "action.ref.methodCode",
    fieldCn: "方法编码",
    type: "String",
    required: true,
    description: "方法唯一标识"
  },
  {
    field: "action.ref.autowiredName",
    fieldCn: "服务变量名",
    type: "String",
    required: true,
    description: "引用的服务变量"
  },
  {
    field: "action.inputParameters",
    fieldCn: "输入参数",
    type: "Array",
    required: false,
    description: "方法入参"
  },
  {
    field: "action.outputParameter",
    fieldCn: "输出参数",
    type: "Object",
    required: false,
    description: "方法返回值"
  }
]
  },
  {
    id: "call-rule",
    nodeType: "call_rule" as NodeType,
    category: "CALL_ACTIVITY" as NodeCategory,
    name: "Rule Call",
    nameCn: "规则调用",
    description: "引用并执行业务规则集",
    jsonConfig: "{\n  \"nodeId\": \"3001\",\n  \"nodeType\": \"rule\",\n  \"sn\": 1,\n  \"nodeName\": \"调用价格计算规则\",\n  \"action\": {\n    \"ruleId\": \"PRICE_CALC_RULE\",\n    \"ruleCode\": \"calculatePrice\",\n    \"inputParams\": {\n      \"amount\": \"${amount}\",\n      \"quantity\": \"${quantity}\"\n    },\n    \"outputParam\": \"calculatedPrice\"\n  }\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: rule"
  },
  {
    field: "action.ruleCode",
    fieldCn: "规则编码",
    type: "String",
    required: true,
    description: "规则唯一标识"
  }
]
  },
  {
    id: "call-service",
    nodeType: "call_service" as NodeType,
    category: "CALL_ACTIVITY" as NodeCategory,
    name: "Service Call",
    nameCn: "服务调用",
    description: "调用远程HTTP/RPC接口服务",
    jsonConfig: "{\n  \"nodeId\": \"2002\",\n  \"nodeType\": \"service\",\n  \"sn\": 2,\n  \"nodeName\": \"调用检查服务\",\n  \"action\": {\n    \"serviceUrl\": \"/api/order/check\",\n    \"serviceMethod\": \"POST\",\n    \"headers\": {\n      \"Content-Type\": \"application/json\"\n    },\n    \"body\": {\n      \"orderNo\": \"${orderNo}\",\n      \"amount\": \"${amount}\"\n    },\n    \"timeout\": 30000\n  }\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: service"
  },
  {
    field: "action.serviceUrl",
    fieldCn: "服务地址",
    type: "String",
    required: true,
    description: "API接口地址"
  },
  {
    field: "action.serviceMethod",
    fieldCn: "请求方法",
    type: "String",
    required: true,
    description: "GET/POST/PUT/DELETE"
  },
  {
    field: "action.body",
    fieldCn: "请求体",
    type: "Object",
    required: false,
    description: "JSON请求参数"
  }
]
  },
  {
    id: "data-check",
    nodeType: "data_check" as NodeType,
    category: "DATA_CHECK" as NodeCategory,
    name: "Data Check",
    nameCn: "数据检查",
    description: "验证输入数据是否符合预设规则",
    jsonConfig: "{\n  \"nodeId\": \"5001\",\n  \"nodeType\": \"check\",\n  \"sn\": 1,\n  \"nodeName\": \"校验订单金额\",\n  \"action\": {\n    \"rules\": [\n      {\n        \"field\": \"amount\",\n        \"validator\": \"greaterThan\",\n        \"value\": 0,\n        \"message\": \"金额必须大于0\"\n      },\n      {\n        \"field\": \"orderNo\",\n        \"validator\": \"notEmpty\",\n        \"message\": \"订单号不能为空\"\n      }\n    ],\n    \"failAction\": \"throwException\"\n  }\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: check"
  },
  {
    field: "action.rules",
    fieldCn: "校验规则",
    type: "Array",
    required: true,
    description: "规则集合"
  },
  {
    field: "action.failAction",
    fieldCn: "失败动作",
    type: "String",
    required: false,
    description: "校验失败后动作"
  }
]
  },
  {
    id: "flow-break",
    nodeType: "flow_break" as NodeType,
    category: "FLOW_STATEMENT" as NodeCategory,
    name: "Break",
    nameCn: "中断",
    description: "强制跳出当前循环结构",
    jsonConfig: "{\n  \"nodeId\": \"1203\",\n  \"nodeType\": \"break\",\n  \"sn\": 3,\n  \"nodeName\": \"中断循环\"\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: break"
  }
]
  },
  {
    id: "flow-continue",
    nodeType: "flow_continue" as NodeType,
    category: "FLOW_STATEMENT" as NodeCategory,
    name: "Continue",
    nameCn: "继续",
    description: "跳过当前循环，进入下一次迭代",
    jsonConfig: "{\n  \"nodeId\": \"1202\",\n  \"nodeType\": \"continue\",\n  \"sn\": 2,\n  \"nodeName\": \"继续下一次循环\"\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: continue"
  }
]
  },
  {
    id: "flow-return",
    nodeType: "flow_return" as NodeType,
    category: "FLOW_STATEMENT" as NodeCategory,
    name: "Return",
    nameCn: "返回",
    description: "结束当前逻辑并返回结果",
    jsonConfig: "{\n  \"nodeId\": \"9001\",\n  \"nodeType\": \"return\",\n  \"sn\": 99,\n  \"nodeName\": \"流程返回计数\",\n  \"action\": {\n    \"val\": \"count\",\n    \"returnType\": \"Integer\",\n    \"receiveVariable\": \"processedCount\"\n  }\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: return"
  },
  {
    field: "action.val",
    fieldCn: "返回值",
    type: "String",
    required: true,
    description: "返回的变量或表达式"
  },
  {
    field: "action.returnType",
    fieldCn: "返回类型",
    type: "String",
    required: true,
    description: "Java类型"
  }
]
  },
  {
    id: "io-end",
    nodeType: "io_end" as NodeType,
    category: "IO_PARAMS" as NodeCategory,
    name: "End Node",
    nameCn: "结束节点",
    description: "流程出口，定义输出参数",
    jsonConfig: "{\n  \"globalOutputParameters\": [\n    {\n      \"sn\": 1,\n      \"parameterId\": \"2002\",\n      \"parameterCode\": \"processedCount\",\n      \"parameterName\": \"处理计数\",\n      \"parameterType\": \"Integer\",\n      \"referenceType\": \"basic\",\n      \"referenceName\": \"整数\",\n      \"referenceId\": \"10\",\n      \"isCollection\": 0,\n      \"isRequired\": 0,\n      \"defaultVal\": 0\n    }\n  ],\n  \"localVariables\": [\n    {\n      \"sn\": 2,\n      \"variableCode\": \"receiptId\",\n      \"variableName\": \"收货单ID\",\n      \"javaType\": \"String\",\n      \"referenceType\": \"dto\",\n      \"referenceName\": \"订单明细DTO\",\n      \"isCollection\": 0\n    }\n  ]\n}",
    excelFields: [
  {
    field: "globalOutputParameters",
    fieldCn: "全局输出参数",
    type: "Array",
    required: true,
    description: "输出参数列表"
  },
  {
    field: "globalOutputParameters[].parameterCode",
    fieldCn: "参数编码",
    type: "String",
    required: true,
    description: "参数唯一标识"
  },
  {
    field: "globalOutputParameters[].parameterType",
    fieldCn: "参数类型",
    type: "String",
    required: true,
    description: "返回类型"
  },
  {
    field: "localVariables",
    fieldCn: "局部变量",
    type: "Array",
    required: false,
    description: "流程内使用的变量"
  }
]
  },
  {
    id: "io-start",
    nodeType: "io_start" as NodeType,
    category: "IO_PARAMS" as NodeCategory,
    name: "Start Node",
    nameCn: "开始节点",
    description: "流程入口，定义输入参数",
    jsonConfig: "{\n  \"flowCode\": \"DemoForeachIfMethod_v2\",\n  \"flowName\": \"示例-遍历判断并调用方法\",\n  \"flowType\": \"service\",\n  \"globalInputParameters\": [\n    {\n      \"sn\": 1,\n      \"parameterId\": \"2001\",\n      \"parameterCode\": \"items\",\n      \"parameterName\": \"待处理集合\",\n      \"parameterType\": \"Object\",\n      \"referenceType\": \"dto\",\n      \"referenceName\": \"订单明细DTO\",\n      \"referenceId\": \"901\",\n      \"referenceCode\": \"snItemDTO\",\n      \"isCollection\": 1,\n      \"isPaging\": 0,\n      \"isRequired\": 1\n    }\n  ]\n}",
    excelFields: [
  {
    field: "flowCode",
    fieldCn: "流程编码",
    type: "String",
    required: true,
    description: "流程唯一标识"
  },
  {
    field: "flowName",
    fieldCn: "流程名称",
    type: "String",
    required: true,
    description: "显示名称"
  },
  {
    field: "globalInputParameters",
    fieldCn: "全局输入参数",
    type: "Array",
    required: true,
    description: "输入参数列表"
  },
  {
    field: "globalInputParameters[].parameterCode",
    fieldCn: "参数编码",
    type: "String",
    required: true,
    description: "参数唯一标识"
  },
  {
    field: "globalInputParameters[].parameterType",
    fieldCn: "参数类型",
    type: "String",
    required: true,
    description: "String/Integer/Object"
  },
  {
    field: "globalInputParameters[].referenceType",
    fieldCn: "引用类型",
    type: "String",
    required: true,
    description: "dto/basic/Object"
  }
]
  },
  {
    id: "logic-judge",
    nodeType: "logic_judge" as NodeType,
    category: "LOGIC_ACTIVITY" as NodeCategory,
    name: "Logic Judge",
    nameCn: "逻辑判断",
    description: "多分支条件判断节点，根据表达式结果执行不同分支",
    jsonConfig: "{\n  \"nodeId\": \"1101\",\n  \"nodeType\": \"if\",\n  \"sn\": 1,\n  \"nodeName\": \"若状态为PAID且金额>0\",\n  \"action\": {\n    \"expr\": \"Objects.equals(item.getStatus(), \\\"PAID\\\") && item.getAmount() != null && item.getAmount() > 0\"\n  },\n  \"nodes\": [\n    {\n      \"nodeId\": \"1201\",\n      \"nodeType\": \"method\",\n      \"nodeName\": \"调用收货方法\"\n    }\n  ]\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: if"
  },
  {
    field: "sn",
    fieldCn: "排序号",
    type: "Integer",
    required: true,
    description: "同层级排序"
  },
  {
    field: "nodeName",
    fieldCn: "节点名称",
    type: "String",
    required: true,
    description: "显示名称"
  },
  {
    field: "action.expr",
    fieldCn: "条件表达式",
    type: "String",
    required: true,
    description: "Java表达式"
  }
]
  },
  {
    id: "loop-array",
    nodeType: "loop_array" as NodeType,
    category: "LOGIC_ACTIVITY" as NodeCategory,
    name: "Array Loop",
    nameCn: "数组遍历",
    description: "遍历集合或数组元素的循环，对每个元素执行逻辑",
    jsonConfig: "{\n  \"nodeId\": \"1001\",\n  \"nodeType\": \"loop\",\n  \"sn\": 1,\n  \"nodeName\": \"遍历订单明细\",\n  \"action\": {\n    \"expr\": \"items\"\n  },\n  \"localVariables\": [\n    {\n      \"variableCode\": \"item\",\n      \"variableName\": \"订单明细元素\",\n      \"variableType\": \"SnItemDTO\",\n      \"referenceType\": \"dto\",\n      \"loopVariableType\": \"self\"\n    }\n  ]\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "action.expr",
    fieldCn: "集合表达式",
    type: "String",
    required: true,
    description: "要遍历的集合"
  },
  {
    field: "localVariables",
    fieldCn: "元素变量",
    type: "Array",
    required: true,
    description: "当前元素变量"
  }
]
  },
  {
    id: "loop-index",
    nodeType: "loop_index" as NodeType,
    category: "LOGIC_ACTIVITY" as NodeCategory,
    name: "Index Loop",
    nameCn: "索引循环",
    description: "基于索引次数的循环结构，控制循环执行次数",
    jsonConfig: "{\n  \"nodeId\": \"1001\",\n  \"nodeType\": \"loop\",\n  \"sn\": 1,\n  \"nodeName\": \"遍历订单明细\",\n  \"action\": {\n    \"expr\": \"orderNumber\"\n  },\n  \"localVariables\": [\n    {\n      \"variableCode\": \"index\",\n      \"variableName\": \"索引\",\n      \"variableType\": \"Integer\",\n      \"loopVariableType\": \"self\"\n    }\n  ]\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: loop"
  },
  {
    field: "action.expr",
    fieldCn: "循环表达式",
    type: "String",
    required: true,
    description: "循环次数表达式"
  },
  {
    field: "localVariables",
    fieldCn: "循环变量",
    type: "Array",
    required: true,
    description: "循环内的局部变量"
  }
]
  },
  {
    id: "object-assign",
    nodeType: "object_assign" as NodeType,
    category: "OBJECT_ACTIVITY" as NodeCategory,
    name: "Object Assign",
    nameCn: "对象赋值",
    description: "修改或设置对象属性值",
    jsonConfig: "{\n  \"nodeId\": \"1202\",\n  \"nodeType\": \"assign\",\n  \"sn\": 2,\n  \"nodeName\": \"计数自增\",\n  \"action\": {\n    \"assignList\": [\n      {\n        \"receiveVariable\": \"count\",\n        \"val\": \"count + 1\",\n        \"valType\": \"expression\"\n      }\n    ]\n  }\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: assign"
  },
  {
    field: "action.assignList",
    fieldCn: "赋值列表",
    type: "Array",
    required: true,
    description: "赋值操作集合"
  },
  {
    field: "action.assignList[].receiveVariable",
    fieldCn: "目标变量",
    type: "String",
    required: true,
    description: "接收赋值的变量"
  },
  {
    field: "action.assignList[].val",
    fieldCn: "值",
    type: "String",
    required: true,
    description: "赋值表达式"
  }
]
  },
  {
    id: "object-mapping",
    nodeType: "object_mapping" as NodeType,
    category: "OBJECT_ACTIVITY" as NodeCategory,
    name: "Parameter Mapping",
    nameCn: "参数映射",
    description: "不同对象间的数据结构转换",
    jsonConfig: "{\n  \"nodeId\": \"4001\",\n  \"nodeType\": \"mapping\",\n  \"sn\": 1,\n  \"nodeName\": \"订单DTO映射\",\n  \"action\": {\n    \"sourceObject\": \"orderDTO\",\n    \"targetObject\": \"saveDTO\",\n    \"fieldMappings\": [\n      {\n        \"sourceField\": \"orderNo\",\n        \"targetField\": \"poNumber\",\n        \"transform\": \"uppercase\"\n      },\n      {\n        \"sourceField\": \"amount\",\n        \"targetField\": \"totalAmount\"\n      }\n    ]\n  }\n}",
    excelFields: [
  {
    field: "nodeId",
    fieldCn: "节点ID",
    type: "String",
    required: true,
    description: "唯一标识"
  },
  {
    field: "nodeType",
    fieldCn: "节点类型",
    type: "String",
    required: true,
    description: "固定值: mapping"
  },
  {
    field: "action.sourceObject",
    fieldCn: "源对象",
    type: "String",
    required: true,
    description: "源数据对象"
  },
  {
    field: "action.targetObject",
    fieldCn: "目标对象",
    type: "String",
    required: true,
    description: "目标数据对象"
  },
  {
    field: "action.fieldMappings",
    fieldCn: "字段映射",
    type: "Array",
    required: true,
    description: "字段对应关系"
  }
]
  }
];

// 按分类分组的节点列表
export const groupedNodeExamples = nodeExamples.reduce((acc, node) => {
  if (!acc[node.category]) {
    acc[node.category] = [];
  }
  acc[node.category].push(node);
  return acc;
}, {} as Record<string, NodeExample[]>);
