const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const CONFIG_DIR = path.join(__dirname, '../src/config');
const OUTPUT_PATH = path.join(__dirname, '../src/lib/node-examples.ts');

function getAllYamlFiles(dir) {
  let results = [];
  const list = fs.readdirSync(dir);
  list.forEach(file => {
    file = path.resolve(dir, file);
    const stat = fs.statSync(file);
    if (stat && stat.isDirectory()) {
      results = results.concat(getAllYamlFiles(file));
    } else {
      if (file.endsWith('.yaml') || file.endsWith('.yml')) {
        results.push(file);
      }
    }
  });
  return results;
}

function parseCsv(content) {
  const lines = content.trim().split('\n');
  if (lines.length < 2) return [];

  const headers = lines[0].split(',').map(h => h.trim());
  const result = [];

  for (let i = 1; i < lines.length; i++) {
    const currentLine = lines[i];
    if (!currentLine.trim()) continue;

    const values = [];
    let inQuotes = false;
    let currentValue = '';

    for (let j = 0; j < currentLine.length; j++) {
      const char = currentLine[j];
      if (char === '"') {
        if (j + 1 < currentLine.length && currentLine[j + 1] === '"') {
          currentValue += '"';
          j++;
        } else {
          inQuotes = !inQuotes;
        }
      } else if (char === ',' && !inQuotes) {
        values.push(currentValue);
        currentValue = '';
      } else {
        currentValue += char;
      }
    }
    values.push(currentValue);

    const obj = {};
    headers.forEach((header, index) => {
      let val = values[index];
      if (header === 'required') {
        val = val === 'true';
      }
      obj[header] = val;
    });
    result.push(obj);
  }
  return result;
}

try {
  // 1. 递归查找所有 YAML 文件
  const files = getAllYamlFiles(CONFIG_DIR);
  const nodes = [];

  console.log(`Found ${files.length} configuration files.`);

  // 2. 读取并解析每个文件
  files.forEach(file => {
    const content = fs.readFileSync(file, 'utf8');
    const nodeData = yaml.load(content);
    
    // 处理 CSV 文件
    const csvPath = file.replace(/\.yaml$|\.yml$/, '.csv');
    if (fs.existsSync(csvPath)) {
      const csvContent = fs.readFileSync(csvPath, 'utf8');
      const excelFields = parseCsv(csvContent);
      
      // 如果 nodeData 是数组，假设 CSV 对应数组里的第一个（这实际上不太常见，因为我们已经拆分了文件）
      // 或者如果拆分后每个文件只有一个对象，则直接赋值
      if (Array.isArray(nodeData)) {
        nodeData.forEach(n => {
           // 简单起见，这里假设 CSV 只对应单个节点，如果是数组则每个节点都用这个 CSV（或者需要更复杂的逻辑）
           // 实际上我们的 split 脚本已经保证了每个文件只有一个对象，所以这里主要处理单个对象
           n.excelFields = excelFields;
        });
        nodes.push(...nodeData);
      } else {
        nodeData.excelFields = excelFields;
        nodes.push(nodeData);
      }
    } else {
      if (Array.isArray(nodeData)) {
        nodes.push(...nodeData);
      } else {
        nodes.push(nodeData);
      }
    }
  });

  // 3. 生成 TS 代码
  const nodeStrings = nodes.map(node => {
    // Stringify jsonConfig if it's an object
    const jsonConfigStr = typeof node.jsonConfig === 'object' 
      ? JSON.stringify(node.jsonConfig, null, 2)
      : node.jsonConfig;

    return `  {
    id: "${node.id}",
    nodeType: "${node.nodeType}" as NodeType,
    category: "${node.category}" as NodeCategory,
    name: "${node.name}",
    nameCn: "${node.nameCn}",
    description: "${node.description}",
    jsonConfig: ${JSON.stringify(jsonConfigStr)},
    excelFields: ${JSON.stringify(node.excelFields || [], null, 2).replace(/"([^"]+)":/g, '$1:')}
  }`;
  });

  const fileContent = `/**
 * This file is auto-generated from src/config/**/*.yaml and *.csv
 * Do not edit this file directly.
 */
import { NodeCategory, NodeType, NodeExample } from "@/types";

export const nodeExamples: NodeExample[] = [
${nodeStrings.join(',\n')}
];

// 按分类分组的节点列表
export const groupedNodeExamples = nodeExamples.reduce((acc, node) => {
  if (!acc[node.category]) {
    acc[node.category] = [];
  }
  acc[node.category].push(node);
  return acc;
}, {} as Record<string, NodeExample[]>);
`;

  fs.writeFileSync(OUTPUT_PATH, fileContent);
  console.log(`Successfully generated src/lib/node-examples.ts with ${nodes.length} nodes.`);

} catch (e) {
  console.error('Error generating node examples:', e);
  process.exit(1);
}
